# Generated by Django 4.1.5 on 2023-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_08_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_08_img',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_08_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='number_09_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_09_img',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_09_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='number_10_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_10_img',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_10_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
