# Generated by Django 4.1.5 on 2023-02-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_post_number_08_desc_post_number_08_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='child_cat',
            field=models.CharField(max_length=50),
        ),
    ]
