# Generated by Django 4.1.5 on 2023-02-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_post_number_08_img_alter_post_number_09_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_08_desc',
            new_name='number_desc_8',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='number_09_desc',
            new_name='number_desc_9',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='number_08_img',
            new_name='number_img_8',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='number_09_img',
            new_name='number_img_9',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='number_10_title',
            new_name='number_title_10',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='number_08_title',
            new_name='number_title_8',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='number_09_title',
            new_name='number_title_9',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number_10_desc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number_10_img',
        ),
        migrations.AddField(
            model_name='post',
            name='number_desc_10',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_img_10',
            field=models.ImageField(default='parent_cat/1.png', upload_to='thumbnail/'),
        ),
    ]
