# Generated by Django 4.1.5 on 2023-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_rename_number_08_desc_post_number_desc_8_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_img_10',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_img_8',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_img_9',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
    ]
