# Generated by Django 4.1.5 on 2023-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_rename_name_post_title_remove_post_number_desc_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='number_desc_10',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_desc_8',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_desc_9',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='number_img_10',
            field=models.ImageField(default='parent_cat/1.png', upload_to='thumbnail/'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_img_8',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_img_9',
            field=models.ImageField(default='parent_cat/1.png', upload_to='parent_cat/'),
        ),
        migrations.AddField(
            model_name='post',
            name='number_title_10',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='number_title_8',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='number_title_9',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='DetailPost',
        ),
    ]
