# Generated by Django 4.1.5 on 2023-02-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_tag_rename_number_desc_10_post_desc_number_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
